default:
  image: cirrusci/flutter:2.8.1
  cache:
    key:
      files:
        - pubspec.lock
    paths:
      - .pub-cache/

stages:
  - lint
  - test
  - coverage

analyze:
  stage: lint
  script:
    - flutter pub get
    - flutter analyze

test:
  stage: test
  script:
    - pub global activate junitreport
    - export PATH="$PATH":"$HOME/.pub-cache/bin"
    - flutter pub get
    - flutter test --coverage --machine | tojunit > testreport.xml
  artifacts:
    reports:
      junit: testreport.xml
    paths:
      - coverage

coverage:
  stage: coverage
  script:
    - flutter test --coverage ./lib
    - lcov -r coverage/lcov.info '*/__test*__/*' -o coverage/lcov_cleaned.info
    - genhtml coverage/lcov_cleaned.info --output=coverage
  artifacts:
    paths:
      - coverage
