default:
  image: cirrusci/flutter:2.8.1
  cache:
    key:
      files:
        - pubspec.lock
    paths:
      - .pub-cache/

stages:
  - lint
  - test
  - coverage
  - build

analyze:
  stage: lint
  script:
    - flutter pub get
    - flutter analyze

test:
  stage: test
  script:
    - pub global activate junitreport
    - export PATH="$PATH":"$HOME/.pub-cache/bin"
    - flutter pub get
    - flutter test --coverage --machine | tojunit > testreport.xml
  artifacts:
    reports:
      junit: testreport.xml
    paths:
      - coverage

coverage:
  stage: coverage
  script:
    - flutter test --coverage ./lib
    - lcov -r coverage/lcov.info '*/__test*__/*' -o coverage/lcov_cleaned.info
    - genhtml coverage/lcov_cleaned.info --output=coverage
  artifacts:
    paths:
      - coverage

build_macos:
  stage: build
  tags: 
    - macos
  before_script:
    - rm -rf dist
    - flutter channel stable
    - flutter upgrade
    - flutter precache
  script:
    - flutter clean
    - flutter pub get
    - flutter build macos --release
  after_script:
    - mkdir -p dist/
    - zip -r dist/TxDx.zip build/macos/Build/Products/Release/TxDx.app
  artifacts:
    paths: 
      - dist


