name: txdx
description: TxDx

publish_to: 'none'

version: 1.0.9+12

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^1.0.3
  jiffy: ^5.0.0
  font_awesome_flutter: ^10.1.0
  file_picker: ^4.3.2
  uuid: ^3.0.4
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  shared_preferences: ^2.0.12
  get: ^4.6.1
  flutter_nord_theme: ^2.1.0
  intl: ^0.17.0
  lit_relative_date_time: ^1.2.0
  url_launcher: ^6.0.20
  package_info_plus: 1.3.0
  flutter_linkify: ^5.0.2
  watcher: ^1.0.1
  quiver: ^3.0.1+1
  scrollable_positioned_list: ^0.2.3
  dropdown_button2: ^1.2.2
  animations: ^2.0.1
  after_layout: ^1.1.0
  macos_secure_bookmarks: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
