name: CI

jobs:
  analyze:
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable' # or: 'beta' or 'master'
    - run: flutter --version
    - run: flutter analyze